# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f1 <- function(x, resSq, n) {
    .Call('_tfHuber_f1', PACKAGE = 'tfHuber', x, resSq, n)
}

rootf1 <- function(resSq, n, low, up, tol = 0.00001, maxIte = 500L) {
    .Call('_tfHuber_rootf1', PACKAGE = 'tfHuber', resSq, n, low, up, tol, maxIte)
}

#' @export
huberMean <- function(X, epsilon = 0.00001, iteMax = 500L) {
    .Call('_tfHuber_huberMean', PACKAGE = 'tfHuber', X, epsilon, iteMax)
}

#' @export
huberReg <- function(X, Y, epsilon = 0.00001, constTau = 1.345, iteMax = 500L) {
    .Call('_tfHuber_huberReg', PACKAGE = 'tfHuber', X, Y, epsilon, constTau, iteMax)
}

sgn <- function(x) {
    .Call('_tfHuber_sgn', PACKAGE = 'tfHuber', x)
}

softThresh <- function(x, lambda) {
    .Call('_tfHuber_softThresh', PACKAGE = 'tfHuber', x, lambda)
}

cmptLambda <- function(beta, lambda) {
    .Call('_tfHuber_cmptLambda', PACKAGE = 'tfHuber', beta, lambda)
}

loss <- function(Y, Ynew, lossType, tau) {
    .Call('_tfHuber_loss', PACKAGE = 'tfHuber', Y, Ynew, lossType, tau)
}

gradLoss <- function(X, Y, beta, lossType, tau) {
    .Call('_tfHuber_gradLoss', PACKAGE = 'tfHuber', X, Y, beta, lossType, tau)
}

updateBeta <- function(X, Y, beta, phi, Lambda, lossType, tau) {
    .Call('_tfHuber_updateBeta', PACKAGE = 'tfHuber', X, Y, beta, phi, Lambda, lossType, tau)
}

cmptPsi <- function(X, Y, betaNew, beta, phi, lossType, tau) {
    .Call('_tfHuber_cmptPsi', PACKAGE = 'tfHuber', X, Y, betaNew, beta, phi, lossType, tau)
}

LAMM <- function(X, Y, Lambda, beta, phi, lossType, tau, gamma) {
    .Call('_tfHuber_LAMM', PACKAGE = 'tfHuber', X, Y, Lambda, beta, phi, lossType, tau, gamma)
}

lasso <- function(X, Y, lambda, phi0 = 0.001, gamma = 1.5, epsilon_c = 0.001, iteMax = 500L) {
    .Call('_tfHuber_lasso', PACKAGE = 'tfHuber', X, Y, lambda, phi0, gamma, epsilon_c, iteMax)
}

huberLasso <- function(X, Y, lambda, tau = -1, constTau = 1.345, phi0 = 0.001, gamma = 1.5, epsilon_c = 0.001, iteMax = 500L) {
    .Call('_tfHuber_huberLasso', PACKAGE = 'tfHuber', X, Y, lambda, tau, constTau, phi0, gamma, epsilon_c, iteMax)
}

getIndex <- function(n, low, up) {
    .Call('_tfHuber_getIndex', PACKAGE = 'tfHuber', n, low, up)
}

getIndexComp <- function(n, low, up) {
    .Call('_tfHuber_getIndexComp', PACKAGE = 'tfHuber', n, low, up)
}

pairPred <- function(X, Y, beta) {
    .Call('_tfHuber_pairPred', PACKAGE = 'tfHuber', X, Y, beta)
}

#' @export
cvHuberLasso <- function(X, Y, lSeq = NULL, nlambda = 30L, constTau = 1.345, phi0 = 0.001, gamma = 1.5, epsilon_c = 0.001, iteMax = 50L, nfolds = 3L) {
    .Call('_tfHuber_cvHuberLasso', PACKAGE = 'tfHuber', X, Y, lSeq, nlambda, constTau, phi0, gamma, epsilon_c, iteMax, nfolds)
}

