# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgn <- function(x) {
    .Call('_adaHuber_sgn', PACKAGE = 'adaHuber', x)
}

f1 <- function(x, resSq, n, rhs) {
    .Call('_adaHuber_f1', PACKAGE = 'adaHuber', x, resSq, n, rhs)
}

rootf1 <- function(resSq, n, rhs, low, up, tol = 0.001, maxIte = 500L) {
    .Call('_adaHuber_rootf1', PACKAGE = 'adaHuber', resSq, n, rhs, low, up, tol, maxIte)
}

huberDer <- function(res, tau, n) {
    .Call('_adaHuber_huberDer', PACKAGE = 'adaHuber', res, tau, n)
}

huberMean <- function(X, n, tol = 0.0001, iteMax = 500L) {
    .Call('_adaHuber_huberMean', PACKAGE = 'adaHuber', X, n, tol, iteMax)
}

huberMeanList <- function(X, tol = 0.0001, iteMax = 500L) {
    .Call('_adaHuber_huberMeanList', PACKAGE = 'adaHuber', X, tol, iteMax)
}

huberMeanVec <- function(X, n, p, epsilon = 0.0001, iteMax = 500L) {
    .Call('_adaHuber_huberMeanVec', PACKAGE = 'adaHuber', X, n, p, epsilon, iteMax)
}

hMeanCov <- function(Z, n, d, N, rhs, epsilon = 0.0001, iteMax = 500L) {
    .Call('_adaHuber_hMeanCov', PACKAGE = 'adaHuber', Z, n, d, N, rhs, epsilon, iteMax)
}

huberCov <- function(X, epsilon = 0.0001, iteMax = 500L) {
    .Call('_adaHuber_huberCov', PACKAGE = 'adaHuber', X, epsilon, iteMax)
}

mad <- function(x) {
    .Call('_adaHuber_mad', PACKAGE = 'adaHuber', x)
}

standardize <- function(X, mx, sx1, p) {
    .Call('_adaHuber_standardize', PACKAGE = 'adaHuber', X, mx, sx1, p)
}

updateHuber <- function(Z, res, der, grad, n, tau, n1) {
    invisible(.Call('_adaHuber_updateHuber', PACKAGE = 'adaHuber', Z, res, der, grad, n, tau, n1))
}

adaHuberReg <- function(X, Y, epsilon = 0.0001, iteMax = 500L) {
    .Call('_adaHuber_adaHuberReg', PACKAGE = 'adaHuber', X, Y, epsilon, iteMax)
}

huberReg <- function(X, Y, epsilon = 0.0001, constTau = 1.345, iteMax = 500L) {
    .Call('_adaHuber_huberReg', PACKAGE = 'adaHuber', X, Y, epsilon, constTau, iteMax)
}

softThresh <- function(x, lambda, p) {
    .Call('_adaHuber_softThresh', PACKAGE = 'adaHuber', x, lambda, p)
}

cmptLambdaLasso <- function(lambda, p) {
    .Call('_adaHuber_cmptLambdaLasso', PACKAGE = 'adaHuber', lambda, p)
}

lossHuber <- function(Z, Y, beta, n1, tau) {
    .Call('_adaHuber_lossHuber', PACKAGE = 'adaHuber', Z, Y, beta, n1, tau)
}

updateHuberHd <- function(Z, Y, beta, grad, n1, tau) {
    .Call('_adaHuber_updateHuberHd', PACKAGE = 'adaHuber', Z, Y, beta, grad, n1, tau)
}

lamm <- function(Z, Y, Lambda, beta, tau, phi, gamma, p, n1) {
    .Call('_adaHuber_lamm', PACKAGE = 'adaHuber', Z, Y, Lambda, beta, tau, phi, gamma, p, n1)
}

huberLasso <- function(Z, Y, lambda, tau, p, n1, phi0 = 0.1, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_adaHuber_huberLasso', PACKAGE = 'adaHuber', Z, Y, lambda, tau, p, n1, phi0, gamma, epsilon, iteMax)
}

huberLassoList <- function(X, Y, lambda, tau, phi0 = 0.1, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_adaHuber_huberLassoList', PACKAGE = 'adaHuber', X, Y, lambda, tau, phi0, gamma, epsilon, iteMax)
}

sparsity <- function(x) {
    .Call('_adaHuber_sparsity', PACKAGE = 'adaHuber', x)
}

adaHuberLasso <- function(Z, Y, lambda, p, phi0 = 0.1, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_adaHuber_adaHuberLasso', PACKAGE = 'adaHuber', Z, Y, lambda, p, phi0, gamma, epsilon, iteMax)
}

adaHuberLassoList <- function(X, Y, lambda, phi0 = 0.1, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_adaHuber_adaHuberLassoList', PACKAGE = 'adaHuber', X, Y, lambda, phi0, gamma, epsilon, iteMax)
}

lossL2 <- function(Z, Y, beta) {
    .Call('_adaHuber_lossL2', PACKAGE = 'adaHuber', Z, Y, beta)
}

cvAdaHuberLasso <- function(X, Y, lambdaSeq, folds, kfolds, phi0 = 0.1, gamma = 1.2, epsilon = 0.001, iteMax = 500L) {
    .Call('_adaHuber_cvAdaHuberLasso', PACKAGE = 'adaHuber', X, Y, lambdaSeq, folds, kfolds, phi0, gamma, epsilon, iteMax)
}

